export const conditionsData = [
  { value: "ADHD", label: "ADHD" },
  { value: "Chronic Gout", label: "Chronic Gout" },
  { value: "Herpes Simplex", label: "Herpes Simplex" },
  { value: "Weak Bladder", label: "Weak Bladder" },
  { value: "Attention-Seeking Disorder", label: "Attention-Seeking Disorder" },
  { value: "Pruritus Ani", label: "Pruritus Ani" },
  { value: "Baldness", label: "Baldness" },
  { value: "Sexual Anxiety", label: "Sexual Anxiety" },
  { value: "Internet Addiction", label: "Internet Addiction" },
  { value: "Muscle Dysmorphia", label: "Muscle Dysmorphia" },
  { value: "Impotence", label: "Impotence" },
  { value: "Foot Odour", label: "Foot Odour" },
  { value: "Nail Fungus", label: "Nail Fungus" },
  { value: "Other", label: "Other" },
];

export const theatreDates = [
  { label: "Saturday 8th June: 8m", value: "Saturday 8th: 8pm" },
  { label: "Sunday 9th June: 4pm", value: "Sunday 9th: 4pm" },
  { label: "Sunday 9th June: 8pm", value: "Sunday 9th: 8pm" },
  { label: "Tuesday 11th June: 8pm", value: "Tuesday 11th: 8pm" },
  { label: "Wednesday 12th June: 8pm", value: "Wednesday 12th: 8pm" },
  { label: "Thursday 13th June: 4pm", value: "Thursday 13th: 4pm" },
  { label: "Thursday 13th June: 8pm", value: "Thursday 13th: 8pm" },
  { label: "Friday 14th June: 8pm", value: "Friday 14th: 8pm" },
  { label: "Saturday 15th June: 4pm", value: "Saturday 15th: 4pm" },
  { label: "Saturday 15th June: 8pm", value: "Saturday 15th: 8pm" },
  { label: "Sunday 16th June: 4pm", value: "Sunday 16th: 4pm" },
  { label: "Sunday 16th June: 8pm", value: "Sunday 16th: 8pm" },
  { label: "Tuesday 18th June: 8pm", value: "Tuesday 18th: 8pm" },
  { label: "Wednesday 19th June:8pm", value: "Wednesday 19th: 8pm" },
  { label: "Thursday 20th June: 8pm", value: "Thursday 20th: 8pm" },
  { label: "Friday 21st June: 8pm", value: "Friday 21st: 8pm" },
  { label: "Saturday 22nd June: 4pm", value: "Saturday 22nd: 4pm" },
  { label: "Saturday 22nd June: 8pm", value: "Saturday 22nd: 8pm" },
  { label: "Sunday 23rd June: 4pm", value: "Sunday 23rd: 4pm" },
  { label: "Sunday 23rd June: 8pm", value: "Sunday 23rd: 8pm" },
];
